### ISSUE TITLE
Keyboard image search

### ISSUE THREAD

**Issue by plasticuser** [Kalidomra/AdamNet-Drive-Emulator#27]
Would it be possible (since the ADAMNet allows every device to snoop every other) that is the keyboard typed an unlikely Hayes-like command (eg: +++ after a three second gap) further typing could be read by the ADE to filter the disk image list down to one or very few images?

**Comment by Kalidomra** [comment]
Intercepting the keyboard commands on ADAMNet is possible. However, the Adam will still register the keystrokes. 
The way the ADE displays the filename on the display is by looking it up on the SD card. It does not keep a list of the current directory filenames, only index numbers. There is not enough memory left on the mega to have a large text array. In order to complete this type of alphabetical sort, it would need to look up each file in the current directory on the SD card. This is too slow and not practical.

**Comment by plasticuser** [comment]
The internal 8K SRAM is quite limiting. What if you had an extra 32K? ;)

**Comment by Kalidomra** [comment]
I do not plan on adding additional memory, The goal of the ADE was to have a hobby level device that anyone can build. Limiting it to a specialized hardware with surface mount components is not what I was trying to achieve.

**Comment by plasticuser** [comment]
Well, it's just a different Arduino board, but yeah, I understand.
